### ISSUE TITLE
install fails on ubuntu 14.04

### ISSUE THREAD

**Issue by TentativeConvert** [umlaeute/v4l2loopback#101]
I am trying to install v4l2loopback on Ubuntu 14.04.3 on a persistent live usb stick.  Is this generally supposed to work?  I’ve tried several options, but I’m only getting error messages.  Here’s some terminal output:

`$ sudo apt-get install v4l2loopback-dkms`
`[………]`
`Preparing to unpack .../v4l2loopback-dkms_0.8.0-1_all.deb ...`
`Building initial module for 3.19.0-25-generic`
**`Traceback (most recent call last):`**
  **`File "/usr/share/apport/package-hooks/dkms_packages.py", line 98, in <module>`**
  **`with apport.fileutils.make_report_file(report) as f:`**
**`AttributeError: 'module' object has no attribute 'make_report_file`**
`Error! Bad return status for module build on kernel: 3.19.0-25-generic (x86_64)`
`Consult /var/lib/dkms/v4l2loopback/0.8.0/build/make.log for more information.`

(I did run `sudo apt-get install linux-headers-$(uname -r)` first, but linux-headers were already up-to-date as expected.  I also tried installing from v4l2loopback-source instead of v4l2loopback-dkms, but that also lead to lots of errors.)

**Comment by TentativeConvert** [comment]
Probably should have posted this error report on launchpad instead of github – I’m very new to the community and don’t yet know my way around.  In any case, the good news is that building the newest version of v4l2loopback from source as supplied here on github worked without any problems.
