### PR TITLE
For upstream/event fix backward compatibility

### PR DESCRIPTION
**Pull request by vicamo**
Found I pushed compatibility fix atop #345 to my gitlab fork for CI instead of github here. With this, v4l2loopback compiles on 3.16 and newer.

### CODE REVIEW

**Comment by vicamo** [comment]
However, some latest commits on develop branch breaks compiling against v4.2 and older:
```
make[1]: Entering directory `/work/vicamo/canonical/dkms/v4l2loopback/v4l2loopback/utils'
cc  -I..   v4l2loopback.c   -o v4l2loopback
v4l2loopback.c: In function '_get_control_id':
v4l2loopback.c:151:29: error: storage size of 'qctrl' isn't known
  struct v4l2_query_ext_ctrl qctrl;
                             ^
v4l2loopback.c:153:19: error: 'VIDIOC_QUERY_EXT_CTRL' undeclared (first use in this function)
  while (ioctl(fd, VIDIOC_QUERY_EXT_CTRL, &qctrl) == 0) {
                   ^
v4l2loopback.c:153:19: note: each undeclared identifier is reported only once for each function it appears in
v4l2loopback.c:158:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (int id = V4L2_CID_USER_BASE; id < V4L2_CID_LASTP1; id++) {
  ^
v4l2loopback.c:158:2: note: use option -std=c99 or -std=gnu99 to compile your code
v4l2loopback.c: In function 'print_conf':
v4l2loopback.c:291:3: warning: format '%s' expects argument of type 'char *', but argument 2 has type 'struct v4l2_loopback_config *' [-Wformat=]
   printf("configuration: %s\n", cfg);
   ^
v4l2loopback.c: In function 'parse_caps':
v4l2loopback.c:492:6: warning: format '%c' expects argument of type 'char *', but argument 3 has type 'char (*)[5]' [-Wformat=]
      &caps->height, &caps->fps_num, &caps->fps_denom) <= 0) {
      ^
v4l2loopback.c:494:7: warning: format '%c' expects argument of type 'char *', but argument 3 has type 'char (*)[5]' [-Wformat=]
       &caps->height, &caps->fps_num) <= 0) {
       ^
v4l2loopback.c:494:7: warning: too many arguments for format [-Wformat-extra-args]
make[1]: *** [v4l2loopback] Error 1
make[1]: Leaving directory `/work/vicamo/canonical/dkms/v4l2loopback/v4l2loopback/utils'
make: *** [utils/v4l2loopback] Error 2
```
