### ISSUE TITLE
fatal error: generated/autoconf.h: No such file or directory

### ISSUE THREAD

**Issue by pickfire** [umlaeute/v4l2loopback#523]
#### Title
Failed to build dkms on linux-cachyos (6.2.2), linux-zen (6.2.2).

### Step 2: Describe your environment

  * `v4l2loopback` version: N/A

  * kernel version: 6.2.2

  * Distribution (+version):

```
-e LSB Version: n/a
-e Distributor ID:      Arch
-e Description: Arch Linux
-e Release:     rolling
-e Codename:    n/a
```

#### Steps to reproduce:

  1. `sudo dkms build -m v4l2loopback -v 0.12.7` (it originally failed on pacman hook, but this is what I run later based on README instructions)

#### Observed Results:

dkms build failed saying it can't find autoconf.h, same results for linux-zen kernel.

```
> sudo dkms build -m v4l2loopback -v 0.12.7
Sign command: /usr/lib/modules/6.2.2-1-cachyos/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
make -j6 KERNELRELEASE=6.2.2-1-cachyos KERNEL_DIR=/usr/lib/modules/6.2.2-1-cachyos/build all...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.2.2-1-cachyos (x86_64)
Consult /var/lib/dkms/v4l2loopback/0.12.7/build/make.log for more information.

> cat /var/lib/dkms/v4l2loopback/0.12.7/build/make.log
DKMS make.log for v4l2loopback-0.12.7 for kernel 6.2.2-1-cachyos (x86_64)
2023年 03月 09日 星期四 23:32:20 +08
Building v4l2-loopback driver...
make -C /usr/lib/modules/6.2.2-1-cachyos/build M=/var/lib/dkms/v4l2loopback/0.12.7/build modules
  CC [M]  /var/lib/dkms/v4l2loopback/0.12.7/build/v4l2loopback.o
In file included from <command-line>:
././include/linux/kconfig.h:5:10: fatal error: generated/autoconf.h: No such file or directory
    5 | #include <generated/autoconf.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:252: /var/lib/dkms/v4l2loopback/0.12.7/build/v4l2loopback.o] Error 1
make[1]: *** [Makefile:2019: /var/lib/dkms/v4l2loopback/0.12.7/build] Error 2
make: *** [Makefile:43: v4l2loopback.ko] Error 2
```

#### Expected Results:

It should build like how it used to build.
