### ISSUE TITLE
DKMS module cannot be installed with Linux 6.13.2

### ISSUE THREAD

**Issue by arkadesOrg** [umlaeute/v4l2loopback#667]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Detail

==> dkms install --no-depmod v4l2loopback/0.15.4 -k 6.13.2-arch1-1

Error! Bad return status for module build on kernel: 6.13.2-arch1-1 (x86_64)
Consult /var/lib/dkms/v4l2loopback/0.15.4/build/make.log for more information.
==> WARNING: `dkms install --no-depmod v4l2loopback/0.15.4 -k 6.13.2-arch1-1' exited 10

### v4l2loopback version

0.15.4

### kernel version

```text
6.13.2
```

**Comment by umlaeute** [comment]
the error says: 
> Consult /var/lib/dkms/v4l2loopback/0.15.4/build/make.log for more information.

which your should do, as this kid file contains crucial information on a what went wrong.

could you stretch this log?

---

**EDIT**  (apparently my cat walked over the keyboard while I typed this; I think what I really meant to say is):

the error says: 
> Consult /var/lib/dkms/v4l2loopback/0.15.4/build/make.log for more information.

which you should do, as this file contains crucial information about what went wrong.

could you provide this log?

**Comment by njcodehub** [comment]
Hey same issue here with the new linux kernel

Here the logs

~~~
 cat /var/lib/dkms/v4l2loopback/0.12.7/build/make.log
DKMS make.log for v4l2loopback-0.12.7 for kernel 7.0.0-28-generic (x86_64)
mar. 21 juil. 2026 09:48:20 CEST
Building v4l2-loopback driver...
make -C /lib/modules/7.0.0-28-generic/build M=/var/lib/dkms/v4l2loopback/0.12.7/build modules
make[1] : on entre dans le répertoire « /usr/src/linux-headers-7.0.0-28-generic »
make[2] : on entre dans le répertoire « /var/lib/dkms/v4l2loopback/0.12.7/build »
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0
warning: pahole version differs from the one used to build the kernel
  The kernel was built with: 125
  You are using:             0
  CC [M]  v4l2loopback.o
v4l2loopback.c: In function ‘v4l2_loopback_open’:
v4l2loopback.c:2089:9: error: too few arguments to function ‘v4l2_fh_add’
 2089 |         v4l2_fh_add(&opener->fh);
      |         ^~~~~~~~~~~
In file included from /usr/src/linux-headers-7.0.0-28-generic/include/media/v4l2-subdev.h:17,
                 from /usr/src/linux-headers-7.0.0-28-generic/include/media/v4l2-device.h:13,
                 from v4l2loopback.c:31:
/usr/src/linux-headers-7.0.0-28-generic/include/media/v4l2-fh.h:97:6: note: declared here
   97 | void v4l2_fh_add(struct v4l2_fh *fh, struct file *filp);
      |      ^~~~~~~~~~~
v4l2loopback.c: In function ‘v4l2_loopback_close’:
v4l2loopback.c:2117:9: error: too few arguments to function ‘v4l2_fh_del’
 2117 |         v4l2_fh_del(&opener->fh);
      |         ^~~~~~~~~~~
/usr/src/linux-headers-7.0.0-28-generic/include/media/v4l2-fh.h:125:6: note: declared here
  125 | void v4l2_fh_del(struct v4l2_fh *fh, struct file *filp);
      |      ^~~~~~~~~~~
make[4]: *** [/usr/src/linux-headers-7.0.0-28-generic/scripts/Makefile.build:289 : v4l2loopback.o] Erreur 1
make[3]: *** [/usr/src/linux-headers-7.0.0-28-generic/Makefile:2115 : .] Erreur 2
make[2]: *** [/usr/src/linux-headers-7.0.0-28-generic/Makefile:248 : __sub-make] Erreur 2
make[2] : on quitte le répertoire « /var/lib/dkms/v4l2loopback/0.12.7/build »
make[1]: *** [Makefile:248 : __sub-make] Erreur 2
make[1] : on quitte le répertoire « /usr/src/linux-headers-7.0.0-28-generic »
make: *** [Makefile:43 : v4l2loopback.ko] Erreur 2
~~~

**Comment by stephematician** [comment]
@njcodehub Looks like it's trying to build on kernel 7.0 (perhaps you have multiple kernels installed on your machine, not just 6.13.2), see this line of your log:

```
make[1] : on entre dans le répertoire « /usr/src/linux-headers-7.0.0-28-generic »
```

For that kernel, you'll need a newer version of _v4l2loopback_. See https://github.com/v4l2loopback/v4l2loopback/issues/669.

**Comment by umlaeute** [comment]
closing this due to lack of feedback from the OP.
